### ISSUE TITLE
bass sprites

### ISSUE THREAD

**Issue by ThatWormStudios** [Gruhlum/BGJ-10#1]
![idle1](https://github.com/Gruhlum/BGJ-10/assets/68815931/216bce10-c351-4f62-a5fd-dcabb74372b2)
![idle2](https://github.com/Gruhlum/BGJ-10/assets/68815931/df93e209-7321-4af2-beec-a811635d234c)
![idle3](https://github.com/Gruhlum/BGJ-10/assets/68815931/88e645ba-5fd2-451a-b73b-9b5791e5fe7b)
![idle4](https://github.com/Gruhlum/BGJ-10/assets/68815931/90c4f70a-0b65-41eb-a7e8-e7c2641e7628)
![idle5](https://github.com/Gruhlum/BGJ-10/assets/68815931/b0496bc0-0588-4dcd-aeb7-d8d5272a832d)
![idle6](https://github.com/Gruhlum/BGJ-10/assets/68815931/9645ab11-4b9b-47c3-85de-64776b7dd58d)
![portrait](https://github.com/Gruhlum/BGJ-10/assets/68815931/e8495b2a-73ef-48b8-9c00-e9bc74df436a)
![walk1](https://github.com/Gruhlum/BGJ-10/assets/68815931/d671fc71-0bf1-4f6c-a38d-2adcb0e0c02c)
![walk2](https://github.com/Gruhlum/BGJ-10/assets/68815931/9588a264-f929-465a-a541-554674f6131f)
![walk3](https://github.com/Gruhlum/BGJ-10/assets/68815931/fa1e5f99-5462-4122-91bc-8e75984752f3)
![walk4](https://github.com/Gruhlum/BGJ-10/assets/68815931/c455d5cb-9b39-4782-a55b-9e2cbd5bf5c9)
![walk5](https://github.com/Gruhlum/BGJ-10/assets/68815931/265ca437-c74e-422f-b3cf-e1f028628d65)
![walk6](https://github.com/Gruhlum/BGJ-10/assets/68815931/c2413416-78ec-4cf7-9ceb-009e9221f6c4)
![walk7](https://github.com/Gruhlum/BGJ-10/assets/68815931/4a5ef459-972f-4d60-b4e4-d804e60b4e7b)
![walk8](https://github.com/Gruhlum/BGJ-10/assets/68815931/f93356b7-f36f-49d6-af72-4c85c504fd60)
![walk9](https://github.com/Gruhlum/BGJ-10/assets/68815931/e20dfe2d-c66f-4041-86f4-d4703959925f)
![walk10](https://github.com/Gruhlum/BGJ-10/assets/68815931/20197199-28ec-437a-a3bc-e85298157670)
![walk11](https://github.com/Gruhlum/BGJ-10/assets/68815931/06ae1c11-a72e-44ec-b033-55a595176806)
![walk12](https://github.com/Gruhlum/BGJ-10/assets/68815931/b3e3cead-c99d-4a84-8fa6-6b0142397f5b)

**Comment by Gruhlum** [comment]
closed
